### ISSUE TITLE
[Roadmap][Move] Hardening and productization

### ISSUE THREAD

**Issue by bob-wilson** [diem/diem#3783]
This issue tracks a set of hardening and productization tasks related to the Move compiler, VM, and related components that we would like to do before launch.

- [x] Protect against stack overflows and OOM errors
- [x] Review errors (codes), error paths, and error conditions
- [x] ~~Annotate MIRAI invariants~~
- [x] VM logging and monitoring for production
- [x] Audit and reduce VM crate dependencies
- [x] Audit error handling
- [x] Create a runbook for debugging problems

**Comment by bob-wilson** [comment]
We completed an audit of the VM crate dependencies. There was an unused dependency on the bytes crate that was removed in #3938, and we stopped using the byteorder crate in #4721

**Comment by bob-wilson** [comment]
We would still like to investigate using MIRAI to annotate invariants in the Move VM but at this point, we're not planning to do that for the current release.

**Comment by bob-wilson** [comment]
We will protect against stack overflows by limiting the recursion depth. This was done in #4993

**Comment by bob-wilson** [comment]
We have finished reviewing the VM validation and execution paths, error codes, and error conditions.

**Comment by bob-wilson** [comment]
With #6237, we are basically done with logging/monitoring work.

**Comment by bob-wilson** [comment]
Marking the error handling audit complete.... We're happy with what we've got now

**Comment by bob-wilson** [comment]
I filled in the content for the runbook in https://github.com/diem/operator-runbooks/pull/54
