### ISSUE TITLE
[network] Benchmark Token Bucket Filter and message throughput

### ISSUE THREAD

**Issue by gregnazario** [diem/diem#6598]
### Tasks
- [x] Test in Libra Swarm / Cluster test to ensure no ill effects
- [x] Tune token bucket filter configuration to ensure the expected throughput isn't throttled
- [x] Identify any bottlenecks that require limits to be imposed
- [x] Determine if `MAX_FRAME_SIZE` is the maximum message size that is properly handled by applications (mempool / state sync)
