### ISSUE TITLE
[State Sync] Improve, simplify and clean up state sync (logic and tests)

### ISSUE THREAD

**Issue by davidiw** [diem/diem#6795]
Last Edit: 2 April
Assigned: Joshua Lind

## Goals
* Harden against DOS attacks and overflows (e.g., arithmetic overflows).
* Fix the race conditions between state sync and consensus (when reading and writing to storage).
* Prevent over-fetches (e.g., to prevent potential node slow downs).
* Let downstream state syncs know about the highest version (to improve overall observability).
* Improve performance for syncing (e.g., optimize chunk fetches and remove redundant computation).
* Focus on testing and hardening failure and edge cases (e.g., retries to prevent livelocks/hangs).
* Simplify and clean up the state sync code base (duplication, dependencies, messy code, etc.).
* Improve overall test coverage, quality and abstractions.
* Design and implement a state sync test harness and set of property tests that can be used across all future state sync versions.
* Improve overall observability and gaps (logs, metrics, counters and alerts).
* Unify the syncing flows (i.e., do we really need 3 different syncing modes if they are all doing the same thing?)

### Task breakdown and week estimate
* [x] (0.5) Use checked arithmetic to harden against overflows/undefined behaviour/crashes.
* [x] (0.5) Update the fuzzer to avoid using mocked implementations (so we're actually testing our code!).
* [x] (0.25) Fix the potential race conditions between state sync and consensus (for storage). 
* [x] (0.5) Add the unit test skeleton to the StateSyncCoordinator (to test previously unchecked but important properties).
* [x] (0.5) Briefly simplify and clean up state sync (duplication, dependencies, messy code and naming).
* [x] (1) Refactor and clean up the integration tests (duplication, dependencies, messy code and naming). 
* [x] (0.5) Fix the consistency issues between naming conventions (e.g., "synchronization" vs "sync").
* [x] (0.25) Update state sync to verify the correctness of chunk requests before sending them to storage (to avoid burning CPU/disk on bad requests).
* [x] (0.25) Update state sync to verify the correctness of chunk responses before trying to commit them (to avoid burning CPU/disk on bad requests).
* [x] (0.25) Make the inter-component timeouts configurable (e.g., with mempool and consensus).
* [x]  (0.25) Fix the flaky/failing integration tests.
* [x]  (0.25) Remove the unnecessary panics/unwraps/expects that should instead be errors (i.e., to prevent possible DOS attacks).
* [x] (0.5) Update error handling to support explicit error types (instead of just random strings). This will allow us to better perform negative testing, reduce dependencies and clean up the code.
* [x] (1) Optimize syncing to a highest ledger info with optimistic fetch.
* [x] (1) Eliminate the ledger info queue and replace it with a single target.
* [x] (1) Unify syncing modes (so we only require 2 sync message types and modes, instead of 3) and send highest known ledger infos on long polls (to help nodes sync more quickly).
* [x] (0.5) Update state sync to provide higher priorities to preferred nodes (based on different roles).
* [x] (0.25) Remove the target syncing behaviour that sends empty chunk responses when the node cannot satisfy the chunk request and replace it with long polling support (to avoid empty/redundant network messages).
* [x] (0.25) Update long polling to support sending the highest known ledger info (this improves long poll syncing by making it support incremental commits).
* [x] (0.25) Audit the logs and remove the overloaded "upstream" term from the code.
* [x] (0.5) Remove the out-of-memory DOS attacks and avoid doing redundant computation on peer selection.

### Tasks that won't be addressed (see reasons alongside each item)
* Sync to waypoint should become verify waypoint alongside syncing to a highest ledger info.
  * Not possible due to breaking changes.
* Always return back the highest ledger info even if in a different epoch.
  * Not possible due to breaking changes.
* Implement request pre-fetching to speed up synchronization when behind a known ledger info.
  * A prototype was implemented in https://github.com/diem/diem/pull/8089, but network instability and the lack of streaming support for state sync meant that we won't land it and instead delegate to the next breaking release.
* Make consensus support a sync to target + highest, and return when highest is achieved.
  * Not high priority and probably won't provide much benefit for now. May need to revisit in the future.
* Design a less intrusive testing infrastructure for state sync that is applicable regardless of implementation details.
  * Not high priority.

### Constraints

It is important that we avoid breaking changes to maintain backward compatibility; we must still support historical clients.

### Related Issues

* Allow validators to use the full nodes to state sync when not in the validator set (i.e., validators currently cannot sync if they are not in the set because they cannot connect to peers). See: https://github.com/diem/diem/issues/5866

## Background 

Today, StateSync operates in three modes:
1. **Sync to a waypoint**: The node has a local version that is less than a known waypoint, so sync to the waypoint.
2. **Sync to a target ledger info**: The node has a local version that is less than a known ledger info, so sync to that ledger info.
3. **Sync to highest available**: The node has a synced version that is the same as the committed version (with proofs in storage) and there is no known ledger info with a higher version, so sync to the highest available.

Note: Mode 3 is also referred to as *the long poll* (because of how it is implemented). Consensus uses mode 2 to sync to a specific target and then expects to resume once the validator is up-to-date.

### 1. Sync to a Waypoint:

1. The waypoint is passed in on state sync creation.
2. The syncing node sends a chunk request with the waypoint version.
3. The syncing node receives a chunk response that contains an epoch ending ledger, waypoint ledger, and a set of transactions with proofs for that waypoint ledger.
4. The syncing node optimistically fetches the next chunk before executing the response from step 3.
5. Execute and update storage using the response from step 3.
6. Complete when synced version >= waypoint version. At this point, if the node is a validator, consensus will step in. Otherwise, the full node will continue using sync to highest (long poll).

### 2. Sync to a Target:

In practice, one would expect that this would be used by both consensus and full nodes, but it is only used by consensus
* The request contains a target ledger info.
* The response contains a response ledger info -- ideally the same as the target ledger info or one that can at least be verified with known trusted state -- as well as transactions with proofs for that ledger info.

### 3. Sync to Highest Available (Long Poll):

* This approach (interestingly) contains syncing to a target but it is used *only* for fullnode state sync.
* The request contains highest known version and an optional target ledger info.
* The response contains transactions with proofs to a response ledger info.
* The response may contain a highest ledger info if a target was provided in the request and the target is within the same epoch.
* If there is a highest ledger info append it to the pending ledger queue -- this is to support early "commits" within an epoch for a node that is behind.

### Miscellaneous Observations

Here's a few miscellaneous observations about state sync:

* Eliminate the pending ledger queue (it's complex and unnecessary): incremental "commit" is debatable in value.
* Always return the highest ledger info that you know about (so that downstream nodes can see how far they are behind).
* Combine the three different flows into as few flows as possible (to avoid re-doing work and code). It may not be possible for a single flow (e.g., due to waypoint targets being versions and not ledger infos).
* Explore supporting a consensus mode that synchronizes to the highest (e.g., if the node is not currently in the validator set). This will require modifications such that consensus can call into state sync iteratively (until it is able to build a 3-chain set of blocks that map to the committed state?)
* StateSync has a maximum chunk size that prevents accidental over-fetches. An over-fetch refers to the case where the total size of a requested set of transactions is larger than what networking (or storage) would allow in a single frame/request. A better approach would be for StateSync to return back the minimum of requested transactions or the most that can fit within a network frame/storage request. In addition, we have already seen at least a 2x improvement in synchronization speed by increasing the chunk size from 2x to 4x, so this could theoretically improve it further and if nothing else should reduce a little load computationally on each side.

**Comment by davidiw** [comment]
As a side project in this task, we should consider unifying the code base on the optimistic follow up: 

https://github.com/libra/libra/blob/master/state-synchronizer/src/coordinator.rs#L1052
should be here https://github.com/libra/libra/blob/master/state-synchronizer/src/coordinator.rs#L1000

we should not call validate_and_store_chunk before sending off the next request

**Comment by davidiw** [comment]
Need to incorporate feedback that consensus first fetches 3 blocks before syncing to a specific version, options:
* Support a flag to sync to a specific version and bail (overlaps with waypoint)
* Improve consensus so that it can support syncing to an arbitrary point

Will update after more research.

**Comment by davidiw** [comment]
I added a notion of chunk limit and over fetching as another project in this space.

**Comment by JoshLind** [comment]
I've also added that we should use checked arithmetic to avoid potential crashes/overflows/undefined behaviour. While it may not be an important issue now, it's probably worth hardening for the future.

**Comment by JoshLind** [comment]
Closing this issue as state sync v1.1 is now wrapped up.
