### ISSUE TITLE
[Tracking Issue] Add script function support to the Diem Framework

### ISSUE THREAD

**Issue by tzakian** [diem/diem#7883]
Now that we have script functions we want to support them in the Diem Framework, and use them to define the set of allowed transactions in the system. The conversion over to this can be broken up (roughly) into the following steps:
1. [x] Add support for ABI generation and documentation generation with script functions **Merged:** #7844 
2. [x] Add support for script functions in the transaction builder code generation. Tracking issue: #7876, PR: #7885 **Merged**
3. [x] Convert the current set of transaction scripts over to script functions PR: #7948 **Merged**
4. [x] Add support for script functions to json-rpc Addressed in #7885 as well
4. [x] Add backwards compatibility mapping from the current set of transaction scripts to the new script functions defined in (3).

**Comment by bob-wilson** [comment]
@tzakian Is this done now?

**Comment by tzakian** [comment]
Yep! Closing now
