### ISSUE TITLE
Tracking Issue for `forge`

### ISSUE THREAD

**Issue by bmwill** [diem/diem#8492]
This is the main tracking issue for the development and rollout of the new `forge` testing framework.

- [x] Initial research into existing test frameworks
- [x] Initial Design of the interfaces for Tests and for Backends
- [ ] Test harness
- [ ] Local Backend
    - [ ] Improve Genesis creation
- [ ] K8s backend
- [ ] Better validator image builds in CI (deprecate codebuild)
- [ ] Migrate existing smoke-tests to Forge
- [ ] Migrate existing cluster-tests to Forge
- [ ] Migrate Json-RPC integration tests to Forge
- [ ] Deprecate and remove smoke-test
- [ ] Deprecate and remove cluster-test
